# Generated by Django 5.0.1 on 2024-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pres',
            field=models.CharField(default=1, max_length=20, verbose_name='Presentación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='Activo', max_length=10, verbose_name='Estatus'),
        ),
    ]
