# Generated by Django 5.0.1 on 2024-06-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_product_pres_alter_client_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Pabasto', 'verbose_name_plural': 'Pabastos'},
        ),
    ]
