# Generated by Django 5.0.1 on 2024-06-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_client_options_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Pabasto', 'verbose_name_plural': 'Pabastos'},
        ),
    ]
