# Generated by Django 5.0.1 on 2024-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='descri',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
