# Generated by Django 5.0.1 on 2024-06-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_sale_descri'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsale',
            name='pres',
            field=models.IntegerField(default=0),
        ),
    ]
