# Generated by Django 5.0.1 on 2024-06-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_detsale_pres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='pres',
            field=models.CharField(max_length=20),
        ),
    ]
