# Generated by Django 5.0.1 on 2024-06-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.sale'),
            preserve_default=False,
        ),
    ]
