# Generated by Django 5.0.1 on 2024-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_factura_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
