# Generated by Django 5.0.1 on 2024-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_factura_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cod',
            field=models.CharField(default=1, max_length=5, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
