# Generated by Django 5.1.2 on 2025-08-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_product_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio'),
        ),
    ]
